// Generated by https://quicktype.io

export interface Siniestro {
  siniestro_id:      number;
  tipo_siniestro:    number;
  beneficiario_id:   number;
  descripcion:       string;
  fecha_siniestro:   string;
  pais_ocurrencia:   string;
  ciudad_ocurrencia: string;
  url_archivo:       string;
}


// Generated by https://quicktype.io

export interface SiniestroPost extends Omit<Siniestro,'siniestro_id'> {
}

export interface SiniestroResp extends Siniestro{
  id : number,
  message ? : string,
}
